sudo: required
services:
  - docker

before_install:
  - docker build -t filoscope/docker-react -f Dockerfile.dev .


script:
  - docker container run filoscope/docker-react npm run test -- --coverage